jasypt: 
  encryptor: 
    password: Abc123

# DataSource Config
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    url: jdbc:p6spy:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    #password: 123456
    #password: ENC(QM+qNMH0NUX/QMFLl8UVBg==)
    #password: Abc123#$%123
    password: ENC(T0lXkKg2WyEgpcvxFu5fO5HsCGCneEed)
  #配置activemq
  activemq:
    #activemq的url
    broker-url: tcp://127.0.0.1:61616
    #用户名
    user: admin
    #密码
    #password: admin
    password: ENC(I+iR2CkREwrKPIFLY4aF7g==)
    #是否使用线程池
    pool:
      enabled: false
    #是否信任所有包
    packages:
      trust-all: true
  #默认情况下，activemq使用的是queue模式，如果要使用topic模式，必须设置为true
  jms:
    pub-sub-domain: false
  ################ Redis 基础配置 ##############  
  redis: 
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #password: redis2019 # Redis服务器连接密码（默认为空）
    password: ENC(wc+w4Pj2QaqcGz5VBitNYwq8ZwSFZqVY) # Redis服务器连接密码（默认为空）
    timeout: 3000 # 链接超时时间 单位 ms（毫秒）
    pool: 
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0

# MP 配置
mybatis-plus:
  type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
  configuration:
    # 3.0.8之前版本问题默认将枚举注册为EnumOrdinalTypeHandler,这是错误的方式,默认是 org.apache.ibatis.type.EnumTypeHandler
    # 如果项目之中实体统一使用IEnum或注解的方式,可配置成 com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler,也可省略上面的type-enums-package配置
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
