jasypt: 
  encryptor: 
    password: Abc123

# DataSource Config
spring:
  profiles:
    active: uat
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    url: jdbc:p6spy:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    #password: 123456
    #password: ENC(QM+qNMH0NUX/QMFLl8UVBg==)
    #password: Abc123#$%123
    password: ENC(T0lXkKg2WyEgpcvxFu5fO5HsCGCneEed)
  #配置activemq
  activemq:
    #activemq的url
    broker-url: tcp://127.0.0.1:61616
    #用户名
    user: admin
    #密码
    #password: admin
    password: ENC(I+iR2CkREwrKPIFLY4aF7g==)
    #是否使用线程池
    pool:
      enabled: false
    #是否信任所有包
    packages:
      trust-all: true
  #默认情况下，activemq使用的是queue模式，如果要使用topic模式，必须设置为true
  jms:
    pub-sub-domain: false
  ################ Redis 基础配置 ##############  
  redis: 
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    #password: redis2019 # Redis服务器连接密码（默认为空）
    password: ENC(wc+w4Pj2QaqcGz5VBitNYwq8ZwSFZqVY) # Redis服务器连接密码（默认为空）
    timeout: 3000 # 链接超时时间 单位 ms（毫秒）
    pool: 
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
################ flyway 配置 ##############  
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    #clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    #  metadata 版本控制信息表 默认 flyway_schema_history
    #table: flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    #baseline-version: 1.0.0
    # 字符编码 默认 UTF-8
    #encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    #out-of-order: false
    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
    schemas: flyway
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    #validate-on-migrate: true

# MP 配置
mybatis-plus:
  type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
  configuration:
    # 3.0.8之前版本问题默认将枚举注册为EnumOrdinalTypeHandler,这是错误的方式,默认是 org.apache.ibatis.type.EnumTypeHandler
    # 如果项目之中实体统一使用IEnum或注解的方式,可配置成 com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler,也可省略上面的type-enums-package配置
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
